### ISSUE TITLE
advise how to turn vsync off

### ISSUE THREAD

**Issue by kparal** [wbasile/Open-Game-Benchmarks#14]
Turning vsync on or off might be more difficult than it seems at a first glance, and I think a quick howto would help a lot of people, especially with opensource drivers. With proprietary drivers, there is usually a toggle somewhere in the proprietary configuration tool, and I also assume in-game options also usually work. However, with opensource drivers, there are no configuration utilities, and the in-game options quite often don't work in my experience (I'm using the radeon driver).

With opensource drivers, you can try to force vsync off by exporting environment variable `vblank_mode=0`, as it is explained [here](http://stackoverflow.com/questions/17196117/disable-vertical-sync-for-glxgears). You can run whole steam like that, and then it applies to all games run from it:

```
vblank_mode=0 steam
```

Unfortunately, it doesn't help always. There's also a `SwapbuffersWait` driver option (also mentioned in that link), the difference is well explained [here](http://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/26564-doubling-your-performance-with-a-simple-trick?p=307404#post307404). It is much harder to configure (using `xorg.conf.d`), it can't be changed during runtime (you have to restart X) and I had no luck when I tried it (vsync was still on for some games), so I wouldn't go into this detail. But at least the `vblank_mode=0` could help people and is easy to use.

If you could expand your http://www.opengamebenchmarks.org/about/ page and add some kind of drop-down button to show instructions how to turn vsync off, I'd add something like this:

---

**Recognizing whether vsync is on or off**

Run the game with a tool to show current FPS (steam overlay, voglperf, glxosd). If your FPS is higher than your monitor refresh rate (60Hz for most monitors), vsync is definitely off. If your FPS is lower, vsync might be on or off, and there's no foolproof way to tell. Try running the game with lowest graphics settings and lowest resolution, that should considerable increase your FPS. If your FPS is still way under your monitor refresh rate, your hardware is probably slow. You can try toggling vsync on and off according to the guide below to see whether it has any effect. If your FPS seems to be exactly your monitor refresh rate (i.e. hovers between 59-61 FPS all the time, with a common monitor), vsync is most probably on, or the game is FPS-locked (the framerate won't exceed your monitor refresh rate, even with disabled vsync).

**Disabling vsync**
1. See the previous section for instructions how to recognize whether vsync is on or off.
2. Many games have an in-game option to toggle vsync. Try it and see whether it makes any difference. For certain combination of games and drivers, this sometimes has no effect.
3. Proprietary drivers come with a configuration tool (AMD or Nvidia configuration center). Use that tool to toggle vsync either globally or for that particular game. Try it and see if it has some effect.
4. Open source drivers do not have configuration tools, but you can sometimes disable vsync by running `vblank_mode=0 game` command. You can easily test this with `vblank_mode=0 glxgears`, you should see `ATTENTION: default value of option vblank_mode overridden by environment` message and reported FPS way over your monitor refresh rate (hundreds or thousands). You can use this even with Steam, so you can run `vblank_mode=0 steam` (make sure to exit it first, if it is already running) and all Steam games should now run with vsync disabled. However, this doesn't unfortunately affect all games, so with some of them, you're out of luck.
5. If you haven't managed to turn vsync off for a certain game, **WHAT NOW?**

---

For the last point, I see two options. Either recommend people to not submit such results, because it would skew the results, or recommend them to submit them anyway (just tell them to include a note that vsync was on), because their contribution is still valuable. I think the second approach would be better, because you'll going to receive vsync-enabled results anyway (some people will not read the recommendation, some people will not understand it, some people will make mistakes, some people are not aware of vsync at all, etc etc), and it's better to see that some game runs on a certain hardware in 60 fps even with vsync on, than not knowing this information at all. Maybe you could write some kind of detection mechanism later, which would tag these kind of results with a flag "vsync probably enabled" or something like that. What do you think?

**Comment by wbasile** [comment]
Excellent suggestions. I think this is appropriate for a section in the "About" page. I think that it is sensible to advise people to upload the benchmark anyway, trying to comment on the impossibility to turn v-sync off. If several benchmark for the same game turn to me mostly at 60fps, for example, it is probable that game itself that is either fps-locked or prevents turning off v-sync.
I'll add the appropriate section in "About" with your writing if that's ok with you.

**Comment by kparal** [comment]
Sure, thank you :)

**Comment by wbasile** [comment]
Section added and issue closed. Thank you very much @kparal !
