### ISSUE TITLE
don't display highest fps submission on the main page

### ISSUE THREAD

**Issue by kparal** [wbasile/Open-Game-Benchmarks#15]
On the main page, I see:

> Highest-fps benchmark: TowerFall Ascension (average FPS = 1354 )

I would not display it here. Neither anywhere else. 

The problem is that it creates a psychological desire to "win the first place" by submitting even higher numbers. Which can then easily lead to people selecting parts of games where they receive highest FPS, but are not relevant to the actual gameplay. Or downright editing their results.

The site should aim to accurately represent the usual performance in different games. Lets not motivate people to submit skewed results. I know it's fun to have something like that there, but I think it's not worth it in the long term.

Maybe there are stats which could be motivating for people yet probably not abusable (too much). For example, if you show a list of people ordered by number of games they benchmarked, it motivates them to benchmark more games. Which is exactly what we want. On the other hand, someone could send the same results to hundreds of games, just to be on the top of the ladder. So I'm not really sure if this is a good statistics either. But at least it motivates people to do more, and not to score more.

What do you think?

**Comment by wbasile** [comment]
I completely agree with you. We already have a sizable amount of data, and I think it is indeed fun to have a box in the home page with some nice statistics; the question is which ones? I can think of:
- most popular game (i.e. game with most benchmarks) (already present)
- most popular GPU and CPU
- N. of registered users (already present)
- Latest 5 game added
- N. of supported Linux games on Steam (already present)
- N. of submitted game benchmarks (already present)

Any idea here is welcome!

**Comment by kparal** [comment]
> most popular game (i.e. game with most benchmarks) (already present)
> most popular GPU and CPU

Good idea. Is that supposed to count how many users have that particular CPU/GPU in one of their systems, or how many times a benchmark was publishes with that CPU/GPU? I think the former is better.

> N. of registered users (already present)
> Latest 5 game added

If you mean just "added to Steam and then synced into OGB list", I don't think it helps much. But maybe "latest (X) game(s) benchmarked for the first time"? That could be more interesting.

> N. of supported Linux games on Steam (already present)
> N. of submitted game benchmarks (already present)

Some of those could be expanded to see a longer list, for example "most popular game" having a link to see more and opening "20 most popular games" would be interesting. The same for popular hardware.

I think it would be fine to show a single line with "most active user" (name and a number of submitted benchmarks), but I would not expand that into a full list.

You could add some stats similar to [GamingOnLinux surveys](https://www.gamingonlinux.com/articles/our-linux-steamos-gamer-survey-results-for-february-2016.6716):
- breakdown of popular display resolutions (derived from defined systems, not benchmarks, because many games have an upper limit)
- breakdown of proprietary vs opensource driver ratio per GPU vendor
- breakdown of popular linux distributions (but you would have to add more of them to the list, at least Red Hat, Suse and Gentoo, see the GOL survey)
- breakdown of desktop environment, but that would require a drop-down with predefined values in the system edit dialog, that might be an overkill

One additional stat that occurred to me was "games desperately needed to be benchmarked", which would show a list of completely unbechmarked games, sorted by their popularity on steam (counted as the number of user comments for that game). But I might be getting too crazy in here :)

**Comment by wbasile** [comment]
>  Is that supposed to count how many users have that particular CPU/GPU in one of their systems, or how many times a benchmark was publishes with that CPU/GPU? I think the former is better.

Yes, the former

> If you mean just "added to Steam and then synced into OGB list", I don't think it helps much. But maybe "latest (X) game(s) benchmarked for the first time"? That could be more interesting.

I was thinking the former, but maybe what you propose is more interesting

> I think it would be fine to show a single line with "most active user" (name and a number of submitted benchmarks)

I don't like this very much, we might go in the direction of "competitiveness" that I don't really like :)

> You could add some stats similar to GamingOnLinux surveys:

I always take part in the GOL survey; from your feedback I got this idea. We might have a small "statistics" box on the front page, pretty much like now (with a few interesting fields), and then a link to a more proper statistics page, with a few graphs and lists. I would limit the mirroring of what is present in GOL though (they have more data points and it was their idea); instead I would have a nice, big link to their latest survey results.

**Comment by wbasile** [comment]
I updated the statistics on the front page according to these ideas so far. I will close this issue for now; other statistics, for example your idea of "most active user", could be considered for a future "gamification" of the site.
