### ISSUE TITLE
Can't add benchmark for Puddle, all text green

### ISSUE THREAD

**Issue by kparal** [wbasile/Open-Game-Benchmarks#17]
I'm trying to add a benchmark for Puddle. When I fill out fields, select the file and hit Save, the page refreshes, all text gets green, but the benchmark is not added. No error message anywhere. This is how the page looks like:
![add-bench-puddle](https://cloud.githubusercontent.com/assets/755451/13475568/040a7630-e0c4-11e5-9af0-f2da21b9e110.png)
(the file was selected before hitting Save)

This is the file I'm trying to upload (zipped, because github):
[voglperf.gameid222140.2016_03_02-22_07_36.csv.zip](https://github.com/wbasile/Open-Game-Benchmarks/files/155662/voglperf.gameid222140.2016_03_02-22_07_36.csv.zip)

**Comment by kparal** [comment]
The same problem for Small World 2 and this file:
[voglperf.gameid235620.2016_03_02-23_28_45.csv.zip](https://github.com/wbasile/Open-Game-Benchmarks/files/155817/voglperf.gameid235620.2016_03_02-23_28_45.csv.zip)

**Comment by kparal** [comment]
Another issue with Solar Flux.

**Comment by kparal** [comment]
Another issue with Ticket to Ride.

**Comment by wbasile** [comment]
Yes, I can replicate the bug. I will look into that immediately.

**Comment by wbasile** [comment]
The issue was the following: both of your Puddle and Small World 2 benchmarks were 59 seconds long (60 is the minimum). This can happen sometimes in voglperf with the commend logfile start 60. I lowered the actual minimum to 59 to prevent this. 
However, there was also a bug in the code that prevented the correct error message to be displayed. Now It should be fixed.

**Comment by kparal** [comment]
Thanks, I did notice that for some submissions of `logfile start 120` the OGB page displayed it as 119 seconds, but I didn't realize it's the same problem here. I guess voglperf can't count correctly :) But it won't be fixed, it's no longer in development, as it seems. Lowering the requirement was the right thing to do.
