### ISSUE TITLE
allow to save and link graphs

### ISSUE THREAD

**Issue by kparal** [wbasile/Open-Game-Benchmarks#19]
I wanted to show [one of the benchmark graphs](http://www.opengamebenchmarks.org/benchmark_detail/387) on my blog. However, it seems that the generated graph image can't be neither saved nor linked, it displays only a grey space. It would be nice if you could generate these images in such a way, that "right click -> save image" or "right click -> get image url" works. If you don't want to allow linking because of bandwidth, at least saving would help. If it's not possible to make "save image" in browser work, maybe add a button to generate and save image somewhere on the page?

**Comment by wbasile** [comment]
With the current implementation (i.e. using the django-graphos package with Flot backend) it is quite laborious to implement this feature; I switched instead to the Highcharts backend with the export module, so it is now possible to save the graphs as PNG and SVG images, as well as print them directly.

**Comment by kparal** [comment]
Pretty cool. Thanks!
