### ISSUE TITLE
Website looks funky and lacks functionality at lower resolutions

### ISSUE THREAD

**Issue by lillelilje** [wbasile/Open-Game-Benchmarks#6]
At lower resolutions some buttons will stop working. In this picture the "Add system" will not respond.
Tested in Chrome, Firefox, Internet Explorer and Edge.
![screenshot3](https://cloud.githubusercontent.com/assets/1491401/12843455/b7e194e8-cbf9-11e5-9b7b-8ab0918c0e1c.png)

Some pictures of the site looking a bit 'off' on lower resolutions:
![screenshot](https://cloud.githubusercontent.com/assets/1491401/12843453/b7cddd7c-cbf9-11e5-8358-c8cf5654c57b.png)
![screenshot2](https://cloud.githubusercontent.com/assets/1491401/12843454/b7cf1f52-cbf9-11e5-9866-10cef364ba11.png)

**Comment by wbasile** [comment]
Buttons were indeed generating some issues with mobile devices and smaller window sizes. I changed the navbar buttons to text links, and encapsulated the tables in the div class "table-responsive".
